export const books = [
    {
        id:1,
        name:'我的天才女友',
        author:'埃莱娜·费兰特',
        imgURL:'https://pic1.zhimg.com/80/v2-85698a9c25512af05c6e629d3c8fa788_1440w.jpg'
    },
    {
        id:2,
        name:'新名字的故事',
        author:'埃莱娜·费兰特',
        imgURL:'https://pic1.zhimg.com/80/v2-85698a9c25512af05c6e629d3c8fa788_1440w.jpg'
    },
    {
        id:3,
        name:'离开的，留下的',
        author:'埃莱娜·费兰特',
        imgURL:'https://pic1.zhimg.com/80/v2-85698a9c25512af05c6e629d3c8fa788_1440w.jpg'
    },
    {
        id:4,
        name:'失踪的孩子',
        author:'埃莱娜·费兰特',
        imgURL:'https://pic1.zhimg.com/80/v2-85698a9c25512af05c6e629d3c8fa788_1440w.jpg'
    },
    {
        id:5,
        name:'成为波伏娃',
        author:'凯特·柯克帕特里克',
        imgURL:'https://images-cn.ssl-images-amazon.cn/images/I/51v4clL-XoL._SX342_SY445_QL70_ML2_.jpg'
    },
    {
        id:6,
        name:'扫地出门',
        author:'马修·德斯蒙德',
        imgURL:'https://m.media-amazon.com/images/I/51MSX7NCzBL.jpg'
    },
    {
        id:7,
        name:'在轮下',
        author:'赫尔曼·黑塞',
        imgURL:'https://easyreadfs.nosdn.127.net/DswrhCtZ9bPfavlqWlVh-Q==/8796093024978789377'
    },
    {
        id:8,
        name:'硅谷是个什么谷',
        author:'虎皮妈',
        imgURL:'https://images-na.ssl-images-amazon.com/images/I/41N8G3vug-L._SX342_SY445_QL70_ML2_.jpg'
    },
    {
        id:9,
        name:'鄙视',
        author:'阿尔贝托·莫拉维亚',
        imgURL:'https://images-cn.ssl-images-amazon.cn/images/I/510efyyw7vL.jpg'
    },
    {
        id:10,
        name:'乐园之丘',
        author:'米尼克·希珀',
        imgURL:'https://images-cn.ssl-images-amazon.cn/images/I/41djMFzu-oL._SX342_SY445_QL70_ML2_.jpg
    },
    {
        id:11,
        name:'不能承受的生命之轻',
        author:'米兰·昆德拉',
        imgURL:'https://covers.zlibcdn2.com/covers299/books/e0/6d/70/e06d70e3061bda2aa1d299632e502db1.jpg',
        textURL:'https://zhuanlan.zhihu.com/p/537320262'
    }
    ,
    {
        id:12,
        name:'猫眼',
        author:'玛格丽特·阿特伍德',
        imgURL:'https://images-cn.ssl-images-amazon.cn/images/I/41U31VvftBL.jpg',
        textURL:'https://zhuanlan.zhihu.com/p/535799934'
    },
    {
        id:13,
        name:'夹缝生存：不堪重负的中产家庭',
        author:'阿莉莎·夸特',
        imgURL:'http://www.sxpdf.com/wp-content/uploads/2022/02/1645086582259.jpg'
    },
    {
        id:14,
        name:'老妓抄',
        author:'冈本加乃子',
        imgURL:'https://images-cn.ssl-images-amazon.cn/images/I/41XRZwLhOiL.jpg',
        textURL:"https://zhuanlan.zhihu.com/p/535822361"
    },
    {
        id:15,
        name:'从零开始的女性主义',
        author:'上野千鹤子 / 田房永子',
        imgURL:'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1635595479l/59485171._SX318_.jpg'
    },
    {
        id:16,
        name:'漫长的告别',
        author:'雷蒙德·钱德勒',
        imgURL:'http://cover.read.duokan.com/mfsv2/download/s010/p01MjapV9dEp/JWKvXv8cOcm02f.jpg!l'
    },
    {
        id:17,
        name:'梁永安：阅读、游历和爱情',
        author:'梁永安',
        imgURL:'https://ebookcn.com/storage/upload/files/000/31/95/27_cover_m.jpg',
        textURL:'https://zhuanlan.zhihu.com/p/537344774?'
    },
    {
        id:18,
        name:'纽约客',
        author:'白先勇',
        imgURL:'https://m.media-amazon.com/images/I/21U0HUbjJyL.jpg'
    },
    {
        id:19,
        name:'逃离',
        author:'爱丽丝·门罗',
        imgURL:'https://tva3.sinaimg.cn/large/007g2d70gy1gd7dyuvmx5j307i0am0sq.jpg'
    },
    {
        id:20,
        name:'达洛维夫人',
        author:'弗吉尼亚·伍尔芙',
        imgURL:"https://img3.bangli.uk/images/cms/2016/11/218445_1.jpg"
    },
    {
        id:21,
        name:'李诞脱口秀工作手册',
        author:'李诞',
        imgURL:"https://images-na.ssl-images-amazon.com/images/I/61nHpQ7pKkL.jpg",
        textURL:"https://zhuanlan.zhihu.com/p/497789327"
    },
    {
        id:22,
        name:'刀锋',
        author: '威廉·萨默赛特·毛姆',
        imgURL:"https://images-cn.ssl-images-amazon.cn/images/I/412OB7vQnoL.jpg"
    },
    {
        id:23,
        name:'山月记',
        author: '中岛敦',
        imgURL:"https://m.media-amazon.com/images/I/418rS18ZRUL.jpg"
    },
    {
        id:24,
        name:'大流感:最致命瘟疫的史诗',
        author:'约翰·M·巴里',
        imgURL:"https://www.gpdf.net/wp-content/uploads/2021/08/20479197-1_u.jpg"
    },
    {
        id:25,
        name:'在路上',
        author:'杰克·凯鲁亚克',
        imgURL:"https://imagepphcloud.thepaper.cn/pph/image/66/254/29.jpg"
    },
    {
        id:26,
        name:'斯通纳',
        author:'约翰·威廉斯',
        imgURL:"http://img1.gtimg.com/cul/pics/hv1/218/26/1990/129406598.jpg",
        textURL:"https://www.zhihu.com/column/c_1480532322252877824"     
    },
    {
        id:27,
        name:'那些忧伤的年轻人',
        author:'F.S.菲茨杰拉德',
        imgURL:"https://m.media-amazon.com/images/I/51TTchQqRFL.jpg"   
    },
    {
        id:28,
        name:'夜色温柔',
        author:'F.S.菲茨杰拉德',
        imgURL:"https://m.media-amazon.com/images/I/41dX1jjL3ML.jpg"   
    },
    {
        id:29,
        name:'教父',
        author:'马里奥·普佐',
        imgURL:"https://cdn.britannica.com/45/171445-050-636F0802/Book-jacket-The-Godfather-Mario-Puzo.jpg"   
    },
    {
        id:30,
        name:'一句顶一万句',
        author:'刘震云',
        imgURL:"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1386228512l/19200550.jpg"   
    },
    {
        id:31,
        name:'罪与罚',
        author:'陀思妥耶夫斯基',
        imgURL:"https://m.media-amazon.com/images/I/51qyn0XNwPL.jpg"   
    },
    {
        id:32,
        name:'约翰·克利斯朵夫',
        author:'罗曼·罗兰',
        imgURL:"http://cover.read.duokan.com/mfsv2/download/fdsc3/p01T5yEjwj4g/oJdRnLBCAGNxz4.jpg!l"
    },
    {
        id:33,
        name:'棋王',
        author:'阿城',
        imgURL:"https://www.stortiktok.com/wp-content/uploads/2021/05/1621952388-672fa6595b65b24.jpg"   
    },
    {
        id:34,
        name:'围城',
        author:'钱钟书',
        imgURL:"https://images-cn.ssl-images-amazon.cn/images/I/51RMtQatx0L.jpg"   
    },
    {
        id:35,
        name:'离婚',
        author:'老舍',
        imgURL:"https://easyreadfs.nosdn.127.net/rThZe4i57zvzQ8Gi5yaFrg==/8796093024901813151"   
    },
    {
        id:36,
        name:'球状闪电',
        author:'刘慈欣',
        imgURL:"http://puui.qpic.cn/vcover_vt_pic/0/pj1003701sklybl/0"
    }
    
];